//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetFinalProject.Models
{
    using COM;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;

    [ComVisible(true)]
    [Guid("95067726-6DA8-408A-851C-A60A961F9480")]
    public partial class Movie : IModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movie()
        {
            this.Rate1 = new HashSet<Rate>();
            this.Comment = new HashSet<Comment>();
            this.Record = new HashSet<Record>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string intro { get; set; }
        public Nullable<int> length { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<float> rate { get; set; }
        public string genres { get; set; }
        public string pictures { get; set; }
        public string regions { get; set; }
        public string stars { get; set; }
        public string directors { get; set; }
        public Nullable<int> likes { get; set; }
        [JsonIgnore]

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rate> Rate1 { get; set; }

        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }

        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Record> Record { get; set; }
    }
}
