//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetFinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rate
    {
        public int user_id { get; set; }
        public int movie_id { get; set; }
        public int score { get; set; }
    
        public virtual Movie Movie { get; set; }
        public virtual User User { get; set; }
    }
}
